FROM ruby:2.6

LABEL maintainer="A. Boudi <abr.boudi@gmail.com>"

RUN apt-get update -yqq \
    && apt-get install -qq -y --no-install-recommends \
    build-essential nodejs libpq-dev ruby-dev graphicsmagick \
    && rm -rf /var/lib/apt/lists

ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

# Install bundler 2
RUN gem install bundler

COPY Gemfile Gemfile.lock $INSTALL_PATH/
RUN bundle install

COPY . $INSTALL_PATH
